on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run
        type: choice
        required: true
        options:
          - dev
          - staging
          - prod
        

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Upgrade pip
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          
      - name: Install Sam and Aws cli
        run:  |
          pip install aws-sam-cli
          pip install awscli
          

      - name: Build the lambda
        run: |
         source venv/bin/activate
         sam build
         ls -ltr
