name: Lambda Pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run
        type: choice
        required: true
        options:
          - dev
          - stg
          - prod
env:
  AWS_REGION: "us-east-1"

jobs:
  lambda_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout Lambda Code
        uses: actions/checkout@v3
        
      - name: Test secret
        run: |
          echo "AWS_ROLE= AWS_ROLE_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - name: Display role name
        run: |
          echo ${{ env.AWS_ROLE }}
          
